name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запускать пайплайн при пуше в ветку master

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Шаг 3: Сделать gradlew исполняемым
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Шаг 4: Собрать проект с помощью Gradle
      - name: Build with Gradle
        run: ./gradlew build  # Сборка проекта и создание JAR-файла

      # Шаг 5: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 6: Собрать Docker-образ
      - name: Build Docker image
        run: docker build -t junepc20/lb4:latest .

      # Шаг 7: Запушить Docker-образ в Docker Hub
      - name: Push Docker image
        run: docker push junepc20/lb4:latest